project_name: argocd-cmp-ytt
release:
  footer: |
    ## Docker Images

    - `postfinance/{{ .ProjectName }}:{{ .Version }}`
builds:
- id: argocd-cmp-ytt
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./plugin.go
  binary: cmp-ytt
  env:
  - CGO_ENABLED=0
dockers:
- image_templates:
  - "postfinance/{{ .ProjectName }}:{{ .Version }}-amd64"
  use: buildx
  dockerfile: packaging/Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
  - --label=org.opencontainers.image.created={{ .Date }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.vendor=PostFinance AG
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.url=https://github.com/postfinance/argocd-cmp
  - --pull
  extra_files:
  - packaging/plugin.yaml
- image_templates:
  - "postfinance/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: packaging/Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - --label=org.opencontainers.image.created={{ .Date }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.vendor=PostFinance AG
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.url=https://github.com/postfinance/argocd-cmp
  - --pull
  extra_files:
  - packaging/plugin.yaml
docker_manifests:
- name_template: postfinance/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - postfinance/{{ .ProjectName }}:{{ .Version }}-amd64
  - postfinance/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: postfinance/{{ .ProjectName }}:latest
  image_templates:
  - postfinance/{{ .ProjectName }}:{{ .Version }}-amd64
  - postfinance/{{ .ProjectName }}:{{ .Version }}-arm64v8
