name: cmp-ytt

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          version: v1.50.1

  build:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
          workdir: ./ytt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snapshot images
        run: |
          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep argocd-cmp-ytt | xargs -I{} docker push  '{}'

      - name: Create and push manifest for :snapshot tag
        run: |
          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep argocd-cmp-ytt | paste -sd ' ' /dev/stdin > images
          docker manifest create postfinance/argocd-cmp-ytt:snapshot $(cat images)
          docker manifest push postfinance/argocd-cmp-ytt:snapshot

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./ytt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
